language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install python-dev python-setuptools
  - sudo apt-get install python3-dev python3-setuptools
  # - sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
  - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
  - sudo apt-get install gcc-4.8 -y
install: pip install -r requirements.txt --cache-dir $HOME/.pip-cache
script:
  - python manage.py test
services:
  - redis-server
cache:
  directories:
    - $HOME/.pip-cache/
    - /var/cache/apt/archives/
notifications:
  email: false