# coding=utf-8

SUCCESS = 1000

EMAIL_INVALID = 1001
PASSWORD_INVALID = 1002
LOGIN_FAILED = 1003
NICKNAME_INVALID = 1004
PASSWORD_NOT_MATCH = 1005
DATA_REQUIRED = 1006
USERNAME_USED = 1007
EMAIL_USED = 1008
CSRF_INVALID = 1009

constants = {
    SUCCESS: 'success',

    EMAIL_INVALID: u'邮箱不符合规范',
    PASSWORD_INVALID: u'密码无效',
    LOGIN_FAILED: u'用户名或密码错误',
    NICKNAME_INVALID: u'昵称不符合规范',
    PASSWORD_NOT_MATCH: u'输入密码不匹配',
    DATA_REQUIRED: u'数据不完全',
    EMAIL_USED: u'邮箱已被注册',
    USERNAME_USED: u'用户名已被注册',
    CSRF_INVALID: u'CSRF 错误'
}

USER_PREFIX = 'USER'

MENDER_PREFIX = 'MENDER'

ADMIN_PREFIX = 'ADMIN'
