"""empty message

Revision ID: 883071433645
Revises: 8c5287419dc5
Create Date: 2017-03-26 13:39:43.114000

"""

# revision identifiers, used by Alembic.
revision = '883071433645'
down_revision = '8c5287419dc5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=128), nullable=True))
    op.drop_constraint(u'users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_1', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
